# cache: bundler
language: objective-c

osx_image: xcode9.4
xcode_project: TextInputFilter.xcodeproj
xcode_scheme: TextInputFilter

script:
  - xcodebuild clean test -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -destination "platform=iOS Simulator,name=iPhone 7,OS=11.4" -quiet

before_install:
  - rvm use $RVM_RUBY_VERSION

install: bundle install --without=documentation --path ../travis_bundle_dir
after_success: bundle exec slather
